-- Backfill subclass tables from app_user role and seed demo-friendly relational data.

-- Ensure every manager-role user has a manager subclass row.
insert into
    public.manager (user_id)
select au.id
from public.app_user au
where
    au.role = 'manager' on conflict (user_id) do nothing;

-- Ensure every player-role user has a player subclass row.
-- When legacy profile data exists, carry it into the relational player record.
insert into
    public.player (
        user_id,
        birthday,
        position,
        height,
        bio,
        url
    )
select au.id, p.birthday, p.position, p.height, p.bio, p.url
from public.app_user au
    left join public.profile p on p.user_id = au.id
where
    au.role = 'player' on conflict (user_id) do
update
set
    birthday = coalesce(
        excluded.birthday,
        public.player.birthday
    ),
    position = coalesce(
        excluded.position,
        public.player.position
    ),
    height = coalesce(
        excluded.height,
        public.player.height
    ),
    bio = coalesce(
        excluded.bio,
        public.player.bio
    ),
    url = coalesce(
        excluded.url,
        public.player.url
    ),
    updated_at = timezone ('utc', now());

-- Seed teams for managers that do not yet own one.
insert into public.team (name, league, location, url, manager_id)
select
    concat('Demo Team ', upper(left(replace(m.user_id::text, '-', ''), 4))),
    'Regional Premier',
    'Demo City',
    concat('https://example.com/team/', left(replace(m.user_id::text, '-', ''), 8)),
    m.user_id
from public.manager m
where not exists (
    select 1
    from public.team t
    where t.manager_id = m.user_id
)
limit 6;

-- Seed one open listing per seeded team if no listing exists yet.
insert into
    public.listing (
        status,
        description,
        position,
        team_id
    )
select 'open', 'Demo listing for MVP testing and presentation flow validation.', 'Central Midfielder', t.id
from public.team t
where
    not exists (
        select 1
        from public.listing l
        where
            l.team_id = t.id
    );

-- Seed player applications to available teams.
-- The unique(player_id, team_id) constraint prevents duplicate application rows.
insert into
    public.application (
        status,
        message,
        player_id,
        team_id
    )
select 'submitted', 'Demo application generated by migration seed.', p.user_id, t.id
from public.player p
    join public.team t on t.manager_id <> p.user_id
where
    not exists (
        select 1
        from public.application a
        where
            a.player_id = p.user_id
            and a.team_id = t.id
    )
limit 20;